import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./Providers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  fontFamily: "GeistSans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  fontFamily: "GeistMono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-family-[${geistSans.fontFamily}] font-family-[${geistMono.fontFamily}] antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
       
      </body>
    </html>
  );
}
